import NewsLetter from '@/components/NewsLetter';
import helper from '@/libs/helper';
import type { Metadata } from 'next';
import { env } from '../../env';

export const metadata: Metadata = {
    title: 'Terms & Conditions | NOBBLE',
    description: 'Tailwind CSS Multipurpose Landing Templates',
    openGraph: {
        ...helper.openGraphData,
        title: 'Terms & Conditions | NOBBLE',
        description: 'Tailwind CSS Multipurpose Landing Templates',
        url: env.NEXT_PUBLIC_APP_URL + '/terms-condition',
        type: 'article',
    },
    twitter: {
        ...helper.twitterData,
        title: 'Terms & Conditions | NOBBLE',
        description: 'Tailwind CSS Multipurpose Landing Templates',
    },
    alternates: {
        canonical: `${env.NEXT_PUBLIC_APP_URL}/terms-condition`,
        languages: { 'x-default': `${env.NEXT_PUBLIC_APP_URL}/terms-condition` },
    },
};

const page = () => {
    return (
        <>
            <div className="overflow-x-hidden pb-16 pt-10 md:pt-16 lg:pb-24">
                <div className="container">
                    <div className="relative mx-auto max-w-[1142px] pb-14 text-center xl:pb-24">
                        <h1
                            className="text-4xl font-extrabold leading-tight text-purple-700 dark:text-white lg:text-[56px]"
                            data-aos="zoom-in"
                            data-aos-duration="1000"
                        >
                            Terms & Condition of NOBBLE
                        </h1>
                    </div>
                    <div className="space-y-12">
                        <div>
                            <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">Terms and Conditions</h2>
                            <div className="space-y-5 leading-[30px]">
                                <p>
                                    This document is an electronic record in terms of Information Technology Act, 200 and rules there under as applicable and
                                    the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act,
                                    20. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                                </p>
                                <p>
                                    His document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries
                                    guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or
                                    usage of careers.padme.com, life. padme.com & blog.padme.com website.
                                </p>
                                <p>
                                    This Website, including all Materials present (excluding any applicable third party materials), is the property of Mantra
                                    and is copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all
                                    copyright laws worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials.
                                </p>
                                <p>
                                    By accessing this website we assume you accept these terms & conditions. Do not continue use website name if you do not
                                    agree to take all of the terms & conditions.
                                </p>
                                <p>
                                    {` The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: “Client”, “You” and “Your” refers
                                    to you, the person log on this website and compliant to the Company's terms and conditions. “The Company” refers to our Company. “Party”, “Parties”, or “Us”,
                                    refers to both the Client and ourselves.`}
                                </p>
                            </div>
                        </div>
                        <div>
                            <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">Cookies</h2>
                            <div className="space-y-5 leading-[30px]">
                                <p>
                                    {
                                        "We employ the use of cookies. By accessing Website Name, you agreed to use cookies in agreement with the Company Name's Privacy Policy."
                                    }
                                </p>
                                <p>
                                    {`Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of
                                    certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.`}
                                </p>
                            </div>
                        </div>
                        <div>
                            <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">License</h2>
                            <div className="space-y-5 leading-[30px]">
                                <p>
                                    Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website
                                    Name. All intellectual property rights are reserved. You may access this from Website Name for your own personal use
                                    subjected to restrictions set in these terms and conditions.
                                </p>
                                <ul className="list-disc ps-7">
                                    <li>Republish material from Website Name</li>
                                    <li>Sell, rent or sub-license material from Website Name</li>
                                    <li>Reproduce, duplicate or copy material from Website Name</li>
                                    <li>Redistribute content from Website Name</li>
                                </ul>
                                <p>
                                    Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the
                                    website. Company Name does not filter, edit, publish or reviewComments prior to their presence on the website. Comments do
                                    not reflect the views and opinions of Company Name, its agents and/or affiliates. Comments reflect the views and opinions of
                                    the person who post their vie
                                </p>
                                <div className="mt-7!">
                                    <h3 className="font-semibold text-purple-700 dark:text-white">You warrant and represent that:</h3>
                                    <ul className="mt-4 list-disc ps-7">
                                        <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so</li>
                                        <li>
                                            The Comments do not invade any intellectual property right, including without limitation copyright, patent or
                                            trademark of any
                                        </li>
                                    </ul>
                                </div>
                                <div className="mt-7!">
                                    <h3 className="font-semibold text-purple-700 dark:text-white">Third party ;</h3>
                                    <ul className="mt-4 list-disc ps-7">
                                        <li>
                                            The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an
                                            invasion of privacy
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div>
                            <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">Hyperlinking to our Content</h2>
                            <div className="space-y-5 leading-[30px]">
                                <p>The following organizations may link to our Website without prior written approval:</p>
                                <ul className="list-disc ps-7">
                                    <li>Government agencies;</li>
                                    <li>Search engines;</li>
                                    <li>News organizations;</li>
                                    <li>
                                        Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other
                                        listed businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping
                                        malls, and charity fundraising groups
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <NewsLetter />
        </>
    );
};

export default page;
